-- CreateEnum
CREATE TYPE "AgentPermission" AS ENUM ('VIEW_CONVERSATIONS', 'SEND_MESSAGES', 'DELETE_MESSAGES', 'ASSIGN_CONVERSATIONS', 'CLOSE_CONVERSATIONS', 'VIEW_CONTACTS', 'CREATE_CONTACTS', 'EDIT_CONTACTS', 'DELETE_CONTACTS', 'EXPORT_CONTACTS', 'VIEW_CAMPAIGNS', 'CREATE_CAMPAIGNS', 'EDIT_CAMPAIGNS', 'DELETE_CAMPAIGNS', 'EXECUTE_CAMPAIGNS', 'VIEW_TEMPLATES', 'CREATE_TEMPLATES', 'EDIT_TEMPLATES', 'DELETE_TEMPLATES', 'VIEW_CANNED_RESPONSES', 'CREATE_CANNED_RESPONSES', 'EDIT_CANNED_RESPONSES', 'DELETE_CANNED_RESPONSES', 'VIEW_ANALYTICS', 'EXPORT_ANALYTICS', 'VIEW_SETTINGS', 'EDIT_SETTINGS', 'VIEW_AGENTS', 'MANAGE_AGENTS');

-- AlterTable
ALTER TABLE "Agent" ADD COLUMN     "password" TEXT,
ADD COLUMN     "permissions" "AgentPermission"[] DEFAULT ARRAY[]::"AgentPermission"[];

-- AddForeignKey
ALTER TABLE "Agent" ADD CONSTRAINT "Agent_adminUserId_fkey" FOREIGN KEY ("adminUserId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
